repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        exclude: ^(frontend/package.json|frontend/package-lock.json|frontend/tsconfig.json)
        args:
          - --autofix
          - --no-ensure-ascii
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        # Exclude paths
        args: [-x=*/test_*.py]
